// import { Feed } from './Feed'
// import { ForgetPassword } from './ForgetPassword'
// import { Login } from './Login'
// import { Register } from './Register'
// import { Upload } from './Upload'
// import { Profile } from './Profile'

export { Feed } from './Feed'
export { ForgetPassword } from './ForgetPassword'
export { Login } from './Login'
export { Register } from './Register'
export { Upload } from './Upload'
export { Profile } from './Profile'
export { Welcome } from './Welcome'
export { Comments } from './Comments'

